on:
  push:
    branches:
      - master # or the name of your main branch
      - main

jobs:
  local-job:
    runs-on: self-hosted
    steps:
      - name: example-step
        run: echo "Hello World!"
